### ISSUE TITLE
Want to use coarse annotation,but don't know something about assembly and disassembly

### ISSUE THREAD

**Issue by kakaguya** [assembly-101/assembly101-annotations#7]
When I used coarse action segmentation, I found that the video files in the recording directory of the dataset you shared did not distinguish between assembly/disassembly, but the above two situations were distinguished in the coarse action segmentation file, which caused me to be unable to obtain accurate action annotations. What is the solution?

**Comment by assembly-101** [comment]
Hi,

In every video, the participant first disassembles an already assembled toy, then proceeds to assemble it again. Due to the inherent differences of temporal ordering of disassembly and assembly, we provide segmentation annotations for them separately. But if you look at the annotation .txts you will see that for disassembly the first action starts at frame 0 (starting of the video) whereas for assembly the first action starts somewhere in the middle of the video.

Hope that answers your question. Please feel free to reach out if you have any more doubts.
